# Enable C++ support
language: cpp

# Ubuntu 14.04 Trusty support
sudo: required

dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6

env: COMPILER=g++-6

before_install:
  - sudo apt-get update -qq

# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
